//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalPayments
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunalServicePrices
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int OrgId { get; set; }
        public double Price { get; set; }
        public string Units { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual CommunalServices CommunalServices { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
