//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalPayments
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommunalPaymentsEntities : DbContext
    {
        public CommunalPaymentsEntities()
            : base("name=CommunalPaymentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommunalServices> CommunalServices { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Payers> Payers { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
    }
}
