//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalPayments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int Id { get; set; }
        public int PayerId { get; set; }
        public System.DateTime OperationDate { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime BillingDate { get; set; }
        public Nullable<double> BeginReadout { get; set; }
        public Nullable<double> EndReadout { get; set; }
        public double AdditionalFee { get; set; }
        public double Total { get; set; }
    
        public virtual CommunalServices CommunalServices { get; set; }
        public virtual Payers Payers { get; set; }
    }
}
