//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalPayments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.MeasurementDevices = new HashSet<MeasurementDevices>();
        }
    
        public int Id { get; set; }
        public int ApartmentId { get; set; }
        public System.DateTime OperationDate { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime BillingDate { get; set; }
        public double AdditionalFee { get; set; }
        public double Total { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual CommunalServices CommunalServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasurementDevices> MeasurementDevices { get; set; }
    }
}
